### ISSUE TITLE
Where are Click Events defined?

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-material-kit#3]
Hey,

I was wondering where the Click events for the Tabs and Actions in the App Bar are set?
I tried to add a slide right/left to switch between tabs instead of only tapping, but can't figure out where the events are in the module. I also couldn't figure out how to set a Click on a Action icon. :(

Any help appreciated!

**Comment by k-vyn** [comment]
The App Bar's actions are under exports.inky in utils. To place the dot at tap, there's three events, only one at a time, that are used to place the dot at the x/y of the click. 

Thank you for pointing out the clicking on action icon. There's a bit of code missing there. I just pushed an update that fixes that. Now, you can write `bar.actions.more_vert`, and it'll work. 👍

**Comment by theposch** [comment]
Awesome! Thanks a ton!
