### ISSUE TITLE
Whats the purpose of these files?

### ISSUE THREAD

**Issue by SarvagyaVaish** [k-vyn/framer-material-kit#4]
I am trying to use the material kit in an existing project. I don't use Framer Studio, so i'm a little confused as to what the minimum set of files I need from your repo is. Also, do you use the framer.js file directly from the Framer repo, or have you modified it? Whats the purpose of framer.generated.js and framer.modules.js?

Any assistance is appreciated! :)
Thanks

**Comment by k-vyn** [comment]
All the files are to make building with it easier. It'd be a single 4,000+ lines of code .coffee file, which would be difficult to edit, so it's broken up into smaller files to scale more efficiently. The material-kit.coffee file builds the module at runtime.
