### ISSUE TITLE
How to define m.utils.inky 

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-material-kit#5]
Sorry, another question.
When i add `m.utils.inky` to a layer, how can i set it up so it doesn't overlap that layer?

See example here:
http://share.framerjs.com/81e3guoi02ui/

I'd like the effect to be constraint within the thumbnail container.

**Comment by k-vyn** [comment]
No worries. On the layer that you added the ink, just set that layer's clip property to true.
