### ISSUE TITLE
Animate constraint relative to element

### ISSUE THREAD

**Issue by theposch** [k-vyn/framer-material-kit#6]
Is there a way to set the constraint like this when animating a constraint?

topLayer.constraints.leading = [myLayer,16]

This is what i'm trying to do:

```
cardText.constraints =
        top: [title, 16]
        leading: 16
        trailing: 16



if setup.image

    thumbnail = new Layer
         superLayer: card
         image: setup.image
         height: setup.imageHeight

    thumbnail.constraints =
             leading:0
         trailing:0
         top: [title, 24]

#   cardText.constraints.top = thumbnail, 16
```

**Comment by k-vyn** [comment]
Yeah, you definitely can. If you've already set constraints on that layer before, you can do the syntax just like that. If you haven't, you need to one extra step:

<pre>
topLayer.constraints = {}
topLayer.constraints.leading = [myLayer, 16]
</pre>

The compiler just needs to know that it's an object before.
